# Generated by Django 2.2.1 on 2019-05-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManage', '0003_auto_20190515_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='duration',
            field=models.IntegerField(default=0, help_text='Tamaño en bytes del flujo', max_length=10),
            preserve_default=False,
        ),
    ]
